server:
  port: 8888
spring:
  application:
    name: accout
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro-server?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: rr998xhz1997
mybatis:
  # 搜索指定包别名
  type-aliases-package: cn.piao888.account
  # 配置mapper的扫描,我到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*Mapper.xml
  #加载全局的配置文件
#  config-location: classpath:mapper/mybatis-config.xml
dubbo:
  application:
    name: dubbo-account-example
  protocol:
    name: dubbo
    port: 8828
  registry:
    id: dubbo-account-example-registry
    address: nacos://127.0.0.1:8848
seata:
  #enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group      # 默认值，有的版本使用 my_test_tx_group
nacos:
  discovery:
    server-addr: localhost:8848