server:
  port: 8080
spring:
  application:
    name: gatway
  security:
    oauth2:
      client:
        registration:
          mall:
            client-id: mall-id
            client-secret: mall-client-secret
        provider:
          mall:
            authorization-uri: https://127.0.0.1:8080/user/oauth2/v1/authorize
            token-uri: https://127.0.0.1:8080/user/oauth2/v1/token
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
  cloud:
    gateway:
      enabled: true
      routes:
        - id: business
          uri: http://localhost:4001
          predicates:
            - Path=/business/**
          filters:
            - StripPrefix= 1
        - id: account
          uri: http://localhost:8888
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix= 1
        - id: order
          uri: http://localhost:8880
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix= 1
        - id: storage
          uri: http://localhost:8881
          predicates:
            - Path=/storage/**
          filters:
            - StripPrefix= 1
        - id: user
          uri: http://localhost:8882
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix= 1