// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BusinessService.proto

package cn.piao888.business.dubbo;

public final class BusinessServiceProto {
  private BusinessServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dubbo_StorageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dubbo_StorageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dubbo_empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dubbo_empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dubbo_OrderDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dubbo_OrderDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025BusinessService.proto\022\005dubbo\"-\n\016Storag" +
      "eRequest\022\014\n\004name\030\001 \001(\t\022\r\n\005count\030\002 \001(\005\"\007\n" +
      "\005empty\"E\n\010OrderDTO\022\016\n\006userId\030\001 \001(\t\022\025\n\rco" +
      "mmodityCode\030\002 \001(\t\022\022\n\norderCount\030\003 \001(\0052A\n" +
      "\016StorageService\022/\n\006deduct\022\025.dubbo.Storag" +
      "eRequest\032\014.dubbo.empty\"\0002<\n\014OrderService" +
      "\022,\n\006create\022\017.dubbo.OrderDTO\032\017.dubbo.Orde" +
      "rDTO\"\000B@\n\031cn.piao888.business.dubboB\024Bus" +
      "inessServiceProtoP\001\210\001\001\242\002\007DEMOSRVb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dubbo_StorageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dubbo_StorageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dubbo_StorageRequest_descriptor,
        new java.lang.String[] { "Name", "Count", });
    internal_static_dubbo_empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dubbo_empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dubbo_empty_descriptor,
        new java.lang.String[] { });
    internal_static_dubbo_OrderDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dubbo_OrderDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dubbo_OrderDTO_descriptor,
        new java.lang.String[] { "UserId", "CommodityCode", "OrderCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
