server:
  port: 8080
logging:
  level:
    org:
      springframework:
        DEBUG
spring:
  application:
    name: gatway
  security:
    oauth2:
      client:
        registration:
          myClient: # 这是一个你选择的客户端名称
            clientId: messaging-client
            clientSecret: rr998xhz1997
            authorizationGrantType: authorization_code
#            redirectUri: http%3A%2F%2Flocalhost%3A9999%2F #获取token后的 回调地址
            redirectUri: http://localhost:9999/
            scope: message.read,message.write
        provider:
          myClient:
            token-uri: http://127.0.0.1:8882/oauth2/token
            authorization-uri: http://127.0.0.1:8882/oauth2/authorize
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
  cloud:
    gateway:
      enabled: true
      routes:
        - id: business
          uri: http://localhost:4001
          predicates:
            - Path=/business/**
          filters:
            - StripPrefix= 1
        - id: account
          uri: http://localhost:8888
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix= 1
        - id: order
          uri: http://localhost:8880
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix= 1
        - id: storage
          uri: http://localhost:8881
          predicates:
            - Path=/storage/**
          filters:
            - StripPrefix= 1
        - id: user
          uri: http://localhost:8882
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix= 1