// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageService.proto

package cn.piao888.storage.dubbo;

public interface emptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:empty)
    com.google.protobuf.MessageOrBuilder {
}
