// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageService.proto

package cn.piao888.storage.dubbo;

public interface PayDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PayDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string money = 2;</code>
   * @return The money.
   */
  java.lang.String getMoney();
  /**
   * <code>string money = 2;</code>
   * @return The bytes for money.
   */
  com.google.protobuf.ByteString
      getMoneyBytes();
}
