// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageService.proto

package cn.piao888.storage.dubbo;

public interface StorageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StorageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 count = 2;</code>
   * @return The count.
   */
  int getCount();
}
