// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageService.proto

package cn.piao888.storage.dubbo;

public final class StorageServiceProto {
  private StorageServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PayDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PayDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024StorageService.proto\"+\n\014HelloRequest\022\014" +
      "\n\004name\030\001 \001(\t\022\r\n\005count\030\002 \001(\005\"\007\n\005empty\"E\n\010" +
      "OrderDTO\022\016\n\006userId\030\001 \001(\t\022\025\n\rcommodityCod" +
      "e\030\002 \001(\t\022\022\n\norderCount\030\003 \001(\005\"\'\n\006PayDTO\022\016\n" +
      "\006userId\030\001 \001(\t\022\r\n\005money\030\002 \001(\t23\n\016StorageS" +
      "ervice\022!\n\006deduct\022\r.HelloRequest\032\006.empty\"" +
      "\00020\n\014OrderService\022 \n\006create\022\t.OrderDTO\032\t" +
      ".OrderDTO\"\0002,\n\016AccountService\022\032\n\005debit\022\007" +
      ".PayDTO\032\006.empty\"\000B1\n\030cn.piao888.storage." +
      "dubboB\023StorageServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloRequest_descriptor,
        new java.lang.String[] { "Name", "Count", });
    internal_static_empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_empty_descriptor,
        new java.lang.String[] { });
    internal_static_OrderDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OrderDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderDTO_descriptor,
        new java.lang.String[] { "UserId", "CommodityCode", "OrderCount", });
    internal_static_PayDTO_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PayDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PayDTO_descriptor,
        new java.lang.String[] { "UserId", "Money", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
