// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StorageService.proto

package cn.piao888.storage.dubbo;

public final class StorageServiceProto {
  private StorageServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StorageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StorageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024StorageService.proto\"-\n\016StorageRequest" +
      "\022\014\n\004name\030\001 \001(\t\022\r\n\005count\030\002 \001(\005\"\007\n\005empty25" +
      "\n\016StorageService\022#\n\006deduct\022\017.StorageRequ" +
      "est\032\006.empty\"\000B4\n\030cn.piao888.storage.dubb" +
      "oB\023StorageServiceProtoP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_StorageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StorageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StorageRequest_descriptor,
        new java.lang.String[] { "Name", "Count", });
    internal_static_empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
