server:
  port: 4001  # 端口号
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro-server?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: rr998xhz1997
  application:
    name: business

seata:
  #enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group      # 默认值，有的版本使用 my_test_tx_group
  service:
    vgroupMapping: # 这里使用 vgroupMapping 和 vgroup-mapping 都可以
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  config:
    type: nacos
    nacos:
      namespace: d6d8f8e5-f986-4856-a2e8-004e60cd373e
      server-addr: localhost:8848
      dataId: seataServer.properties
      group: SEATA_GROUP
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: dubbo-business-example-registry
    address: nacos://127.0.0.1:8848
  consumer:
    check: false
nacos:
  discovery:
    server-addr: localhost:8848