// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

package cn.piao888.account.dubbo;

public final class AccountServiceProto {
  private AccountServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dubbo_empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dubbo_empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dubbo_OrderDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dubbo_OrderDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dubbo_PayDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dubbo_PayDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024AccountService.proto\022\005dubbo\"\007\n\005empty\"E" +
      "\n\010OrderDTO\022\016\n\006userId\030\001 \001(\t\022\025\n\rcommodityC" +
      "ode\030\002 \001(\t\022\022\n\norderCount\030\003 \001(\005\"\'\n\006PayDTO\022" +
      "\016\n\006userId\030\001 \001(\t\022\r\n\005money\030\002 \001(\t2<\n\014OrderS" +
      "ervice\022,\n\006create\022\017.dubbo.OrderDTO\032\017.dubb" +
      "o.OrderDTO\"\00028\n\016AccountService\022&\n\005debit\022" +
      "\r.dubbo.PayDTO\032\014.dubbo.empty\"\000B>\n\030cn.pia" +
      "o888.account.dubboB\023AccountServiceProtoP" +
      "\001\210\001\001\242\002\007DEMOSRVb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dubbo_empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dubbo_empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dubbo_empty_descriptor,
        new java.lang.String[] { });
    internal_static_dubbo_OrderDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dubbo_OrderDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dubbo_OrderDTO_descriptor,
        new java.lang.String[] { "UserId", "CommodityCode", "OrderCount", });
    internal_static_dubbo_PayDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dubbo_PayDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dubbo_PayDTO_descriptor,
        new java.lang.String[] { "UserId", "Money", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
