// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

package cn.piao888.account.dubbo;

public interface emptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dubbo.empty)
    com.google.protobuf.MessageOrBuilder {
}
