// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

package cn.piao888.account.dubbo;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dubbo.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 count = 2;</code>
   * @return The count.
   */
  int getCount();
}
