// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountService.proto

package cn.piao888.account.dubbo;

public interface OrderDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dubbo.OrderDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string commodityCode = 2;</code>
   * @return The commodityCode.
   */
  java.lang.String getCommodityCode();
  /**
   * <code>string commodityCode = 2;</code>
   * @return The bytes for commodityCode.
   */
  com.google.protobuf.ByteString
      getCommodityCodeBytes();

  /**
   * <code>int32 orderCount = 3;</code>
   * @return The orderCount.
   */
  int getOrderCount();
}
