// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderService.proto

package cn.piao888.order.dubbo;

/**
 * Protobuf service {@code OrderService}
 */
public  abstract class OrderService
    implements com.google.protobuf.Service {
  protected OrderService() {}

  public interface Interface {
    /**
     * <code>rpc create(.OrderDTO) returns (.OrderDTO);</code>
     */
    public abstract void create(
        com.google.protobuf.RpcController controller,
        cn.piao888.order.dubbo.OrderDTO request,
        com.google.protobuf.RpcCallback<cn.piao888.order.dubbo.OrderDTO> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new OrderService() {
      @java.lang.Override
      public  void create(
          com.google.protobuf.RpcController controller,
          cn.piao888.order.dubbo.OrderDTO request,
          com.google.protobuf.RpcCallback<cn.piao888.order.dubbo.OrderDTO> done) {
        impl.create(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.create(controller, (cn.piao888.order.dubbo.OrderDTO)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return cn.piao888.order.dubbo.OrderDTO.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return cn.piao888.order.dubbo.OrderDTO.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc create(.OrderDTO) returns (.OrderDTO);</code>
   */
  public abstract void create(
      com.google.protobuf.RpcController controller,
      cn.piao888.order.dubbo.OrderDTO request,
      com.google.protobuf.RpcCallback<cn.piao888.order.dubbo.OrderDTO> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return cn.piao888.order.dubbo.OrderServiceProto.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.create(controller, (cn.piao888.order.dubbo.OrderDTO)request,
          com.google.protobuf.RpcUtil.<cn.piao888.order.dubbo.OrderDTO>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return cn.piao888.order.dubbo.OrderDTO.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return cn.piao888.order.dubbo.OrderDTO.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends cn.piao888.order.dubbo.OrderService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void create(
        com.google.protobuf.RpcController controller,
        cn.piao888.order.dubbo.OrderDTO request,
        com.google.protobuf.RpcCallback<cn.piao888.order.dubbo.OrderDTO> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        cn.piao888.order.dubbo.OrderDTO.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          cn.piao888.order.dubbo.OrderDTO.class,
          cn.piao888.order.dubbo.OrderDTO.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public cn.piao888.order.dubbo.OrderDTO create(
        com.google.protobuf.RpcController controller,
        cn.piao888.order.dubbo.OrderDTO request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public cn.piao888.order.dubbo.OrderDTO create(
        com.google.protobuf.RpcController controller,
        cn.piao888.order.dubbo.OrderDTO request)
        throws com.google.protobuf.ServiceException {
      return (cn.piao888.order.dubbo.OrderDTO) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        cn.piao888.order.dubbo.OrderDTO.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:OrderService)
}

